server:
  port: 8765
# настройки путей для микросервисов с бизнес-логикой
spring:
  cloud:
    gateway:
      routes:
        - id: notes-service
          uri: http://localhost:8081/
          predicates:
            - Path=/notes-service/**
        - id: rest-service
          uri: http://localhost:8082/
          predicates:
            - Path=/rest-service/**